### ISSUE TITLE
Flying causes game crash?

### ISSUE THREAD

**Issue by AlexisBloodwood** [Draylar/identity#118]
Playing in 1.16.5, game loaded fine as well as the mod until I tried to fly. No idea what happened but both Flying Pig from BetterNether and the Blaze caused a crash.

<details>
  <summary>Game Log, hastebin wouldn't save</summary>
 

  ```[12:00:03] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:91) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_1545 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_1545 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @d554c5f)
	at net.minecraft.class_1297.handler$caa000$sneakingActivate(class_1297.java:7133) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1297.method_5660(class_1297.java) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at draylar.identity.cca.IdentityComponent.tickIdentity(IdentityComponent.java:115) ~[identity-1.11.3-beta-1.16.4.jar:?]
	at draylar.identity.cca.IdentityComponent.serverTick(IdentityComponent.java:98) ~[identity-1.11.3-beta-1.16.4.jar:?]
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickComponents(Unknown Source) ~[?:?]
	at net.minecraft.class_3218.handler$bde000$tick(class_3218.java:1575) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-minecraft-1.16.5-client.jar:?]
	... 5 more
[12:00:03] [Server thread/INFO]: Stopping server
[12:00:03] [Server thread/INFO]: Saving players
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/22/21, 12:00 PM
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1545 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_1545 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @d554c5f)
	at net.minecraft.class_1297.handler$caa000$sneakingActivate(class_1297.java:7133)
	at net.minecraft.class_1297.method_5660(class_1297.java)
	at draylar.identity.cca.IdentityComponent.tickIdentity(IdentityComponent.java:115)
	at draylar.identity.cca.IdentityComponent.serverTick(IdentityComponent.java:98)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickComponents(Unknown Source)
	at net.minecraft.class_3218.handler$bde000$tick(class_3218.java:1575)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:834)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1297.handler$caa000$sneakingActivate(class_1297.java:7133)
	at net.minecraft.class_1297.method_5660(class_1297.java)
	at draylar.identity.cca.IdentityComponent.tickIdentity(IdentityComponent.java:115)
	at draylar.identity.cca.IdentityComponent.serverTick(IdentityComponent.java:98)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickComponents(Unknown Source)
	at net.minecraft.class_3218.handler$bde000$tick(class_3218.java:1575)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 146
	Entity Name: AlexisBloodwood
	Entity's Exact location: -314.05, 94.85, -4574.00
	Entity's Block location: World: (-315,94,-4574), Chunk: (at 5,5,2 in -20,-286; contains blocks -320,0,-4576 to -305,255,-4561), Region: (-1,-9; contains chunks -32,-288 to -1,-257, blocks -512,0,-4608 to -1,255,-4097)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_3222['AlexisBloodwood'/146, l='ServerLevel[New World]', x=-314.05, y=94.85, z=-4574.00]]
	Chunk stats: ServerChunkCache: 4275
	Level dimension: minecraft:overworld
	Level spawn location: World: (-116,63,-4), Chunk: (at 12,3,12 in -8,-1; contains blocks -128,0,-16 to -113,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2928037 game time, 3193033 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:834)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-62-generic
	Java Version: 11.0.9.1, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 1979812344 bytes (1888 MB) / 4555014144 bytes (4344 MB) up to 6308233216 bytes (6016 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xms1152m -Xmx6016m
	Fabric Mods: 
		adabraniummod: Adabranium 1.3.2+1.16.5
		adapaxels: AdaPaxels 1.0.6+1.16.5
		additionalbars: Additional Bars 1.0.0
		advancements-enlarger: Advancements Enlarger 0.2.3
		afktape: AFKTape 1.1.1
		allstackable: All Stackable 1.3.0
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		artifice: Artifice 0.14.4+1.16.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		bedspreads: Bedspreads 1.3.1-1.16.4
		better_mod_button: Better Mod Button 1.1.4
		better_wandering_trader: Better Wandering Trader 1.6.2
		better_wither_skeletons: Better Wither Skeletons 1.1.0
		betterend: Better End 0.8.8-beta
		betterf3: BetterF3 1.1.1
		betternether: Better Nether 5.0.5
		blackstonetools: Blackstone Tools 1.2.0+1.16.1
		blame: Blame 2.2.6
		blue_endless_jankson: jankson 1.2.0
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.2
		cavebiomes: Cave Biomes 0.5.1
		celib: Celib - CebbyS Library Mod 0.2.0_1.16.4
		chainmail: Chainmail 0.5.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.6
		cmdkeybind: Command Macros 1.5.2-1.16
		coloredslime: Colored Slime Blocks 1.0
		columns: Columns 1.1.1
		com_github_javafactorydev_lightningstorage: LightningStorage 3.1.8
		com_oneandone_composite-jks: composite-jks 1.0
		comforts: Comforts 0.0.1-1.16.4
		convenient-mobgriefing: Convenient mobGriefing 1.1.4
		craftingpad: Crafting Pad 1.16.4-fabric0.25.1-1.0.5
		crowdin-translate: CrowdinTranslate 1.2
		cultivation: Cultivation 0.0.72
		curioofundying: Curio of Undying 1.1.1-1.16.5
		curios: Curios API 0.0.11-1.16.4
		diamold: Diamold 1.1.1+1.16.4
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		discerning_furnace: Discerning Furnace 1.0.1+MC1.16.1-1.16.5
		dontdropit: Don't Drop It! 2.2.0+1.16
		earthtojavamobs: Earth2Java 1.6.1+1.16.4
		easiervillagertrading: EasierVillagerTrading 1.16.4-fabric0.25.1-1.5.3
		editsign: Edit Sign 2.2.0
		eggtab: Egg Tab 1.3.2+1.16-fabric
		emerald_tools: Emerald Tools 1.1.1
		enderitemod: Enderite Mod 1.2.2
		expandedstorage: ExpandedStorage 5.6.32
		fabriblocks: FabriBlocks 1.2.1
		fabric: Fabric API 0.29.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-diagonal-panes: Fabric Diagonal Panes 0.4.0
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fallflyinglib: FallFlyingLib 1.1.0
		fastgrowth: FastGrowth 1.3
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-2
		flonters: Flonters 1.1.1+1.16.2
		fullbellysheep: Full Belly Sheep 1.1.0
		gbfabrictools: GBfabrictools 1.2.2+1.16
		gildednetherite: Gilded Netherite 1.6.0
		grabcraft-downloader: GrabcraftLitematic 1.16.4-fabric0.25.1-0.3
		gravel-ores: Gravel Ores 1.2.0+1.16.2
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		healthoverlay: Health Overlay 3.6.14
		hotfurnace: Hot Furnace 1.1.1
		identity: Identity 1.11.3-beta-1.16.4
		infinitevillagertrading: InfiniteVillagerTrading 1.16.2-fabric0.17.2-1.1
		instantfertilization: Instant Fertilization 1.0.0
		instantlava: InstantLava 1.2.1
		io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.7.9
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 11
		kyrptconfig: Kytpt Config 1.1.5-1.16
		ladderwarp: LadderWarp 1.1.0+1.16.x
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
		libblockattributes_items: LibBlockAttributes (Items) 0.8.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		libstructure: LibStructure 1.5
		lightstones: Lightstones 1.2
		lionutils: LionUtils 7.0.0+1.16
		litematica: Litematica 0.0.0-dev.20210120.213004
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		mechanix: Mechanix 3.3.0
		minecraft: Minecraft 1.16.5
		minegate-moreblocks: MineGate - MoreBlocks 1.0.2
		miniextras: Mini Extras Mod 1.2.1
		mo_glass: Mo Glass 1.5-MC1.16.5
		mobropes: Mob Ropes 1.16.4+1.0.2
		modmenu: Mod Menu 1.14.13+build.19
		more_gems: More Gems 1.1.21
		morepotions: More Potions 1.0.0
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		multi_item_lin: Multi Item Lin 1.0.0
		nenchantfix: Nile Enchantment Fix 3.0.0
		nicetohave: Nice to Have 1.3.5
		nomoreglowingpots: No More Glowing Pots 1.0.2
		notrample: No Trample 0.0.2
		oaktree: Oak Tree 0.4.2-beta
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		origins: Origins 0.4.5
		oro_config: OroArmor Config -0df99c92b1-1
		overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
		overpowered_mending: Overpowered Mending 2.2.2
		parakeetmod: The Parakeet Mod 1.16.3-1.0.6
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16.4-48-FABRIC
		pconfig: Paradox Config 0.3.6-alpha
		phosphor: Phosphor 0.6.0+build.7
		piglib: Piglib 1.0.1
		plantinajar: Plant In A Jar 1.8.1
		playerabilitylib: Pal 1.2.1
		protos: Protos 1.0.1
		pulverizer_mod: Pulverizer Mod 1.1.1
		quickshulker: Quick Shulker 1.1.10-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		redbits: RedBits 1.6.0
		replaymod: Replay Mod 1.16.4-2.5.1
		reroll: Reroll 1.1.0-1.16.4
		roughlyenoughitems: Roughly Enough Items 5.8.11
		roughlyenoughitems-api: REI (API) 5.8.11
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.11
		roughlyenoughitems-runtime: REI (Runtime) 5.8.11
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		shelf: Shelf 1.0.0
		shulkerboxtooltip: Shulker Box Tooltip 2.3.4+1.16.4
		shutupmod: Shut Up! 0.0.1-1.16.2
		simplemeasuring: Simple Measuring 1.0.0
		skinnedlanterns: Skinned Lanterns 1.16.4-1.1.1
		skinshine: Skin Shine 1.1.5
		slabref: Refabricated Slabs 0.3.0
		slotlink: slotlink 2.2.0+1.16.4
		smart_pipes: Smart Pipes 1.0.2
		smootherbedrock: Smoother Bedrock 1.0.0
		somnus: Somnus API 0.0.10-1.16.4
		sonicdevices: Sonic Devices 1.4.0+1.16.1
		sonicdevicesapi: Sonic Devices API 1.2.0
		supernaturalcrops: Supernatural Crops 1.0.5
		team_reborn_energy: Energy 0.1.1
		telekinesis: Telekinesis Enchantment 1.1.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		tooltipfix: ToolTip Fix 1.0.2-1.16
		toomanybinds: Too Many Binds 0.3.0+1.16.3
		totemmod: Wither Totems Mod 0.3.2
		totemplus: Totem Plus 1.0.1
		trinket-heart-canisters: Trinket Heart Canisters 1.0.0
		trinkets: Trinkets 2.6.7
		ttkb: TTKB 1.0.2
		unknownrecipes: UnknownRecipeSilencer 1.0.0
		verticalredstone: Vertical Redstone 1.2.0-beta1
		waila: Hwyla 1.9.22
		whereisit: Where Is It 1.9.1
		winged: Winged Mod 1.16.2-1.4.1
		wither_proof_block: Wither Proof Block 1.0.2
		woodcutter: Woodcutter 1.2-1.16.1
		worldedit: WorldEdit 7.2.0+a51fa43
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 21.1.0
		xaeroworldmap: Xaero's World Map 1.11.9
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['AlexisBloodwood'/146, l='ServerLevel[New World]', x=-314.05, y=94.85, z=-4574.00]]
	Data Packs: file/anti enderman grief v1.1.0.zip, file/anti creeper grief v1.1.0.zip, vanilla (incompatible), slabref:pack, file/armor statues v2.8.1.zip, Fabric Mods, file/anti ghast grief v1.1.0.zip, file/bac_advancements, file/cauldron concrete v2.0.3.zip, file/chunk loaders v1.0.1.zip, file/classic fishing loot v1.1.0.zip, file/coordinates hud v1.2.0.zip, file/custom nether portals v2.3.2.zip, file/custom villager shops v1.2.0.zip, file/fast leaf decay v2.0.3.zip, file/graves v2.8.0.zip, file/larger phantoms v1.2.1.zip, file/more mob heads v2.8.2.zip, file/nether portal coords v1.1.0.zip, file/redstone rotation wrench v1.1.0.zip, file/terracotta rotation wrench v1.1.0.zip, file/thunder shrine v1.1.0.zip, file/treasure gems v1.2.0.zip, file/VanillaTweaks_c367345.zip, file/wandering trades hermit edition v1.4.0.zip, file/Reverse_Craft.zip (incompatible), file/timber v2.1.1.zip, file/more-recipes-v2-0-0.zip, file/double shulker shells v1.3.0.zip, file/dragon drops v1.3.0.zip, file/gem villagers v4.3.1.zip, file/silence mobs v1.1.0.zip, file/xp management v1.1.0.zip, file/ichphilipp-s-endcity-v1-1-1-16-2.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
#@!@# Game crashed! Crash report saved to: #@!@# /home/bloodwoodsrisen/.local/share/multimc/instances/1.16.4/.minecraft/crash-reports/crash-2021-01-22_12.00.03-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
  ```
  
</details>

**Comment by James103** [comment]
Identity supports MC versions up to 1.16.4 according to [the release page](https://www.curseforge.com/minecraft/mc-mods/identity). Can you try downgrading Minecraft to 1.16.4 and removing all other mods but Fabric API and Identity?

**Comment by AlexisBloodwood** [comment]
Yup! That worked fine; latest update of Identity and version 0.29.4 of Fabric API.

**Comment by Draylar** [comment]
I think this is [FastGrowth's](https://github.com/uiytt/FastGrowth/blob/d099f938750ac91b254688bb3e0e86cbd334e003/src/main/java/fr/uiytt/fastgrowth/mixin/PlayerShiftEvent.java) problem, because their mixin is doing an unchecked cast to `PlayerEntity` (which is what is crashing).
