### ISSUE TITLE
Ender Dragon disconnects you

### ISSUE THREAD

**Issue by ghost** [Draylar/identity#120]
If you try to use the Ender Dragon ability it disconnects you without doing anything. I am playing on a 1.16.4 server with fabric and only Identity and fabric api mods.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/77891235/105606628-cff1a900-5d9a-11eb-8b3a-3cca0395b5e5.png) this is what happens when you press the ability key. No message whatsoever.

**Comment by James103** [comment]
Do you have the logs (server and client if possible)? If so, can you post them here? Don't use Hastebin as it returns an internal server error. Instead, put your logs in this format:
```
<details>

<summary> Logs </summary>

Put your logs here

</details>
```

**Comment by PufflePup** [comment]
I could get server logs but how do you get client logs? 
`[16:57:03] [Netty Epoll Server IO #2/ERROR]: Encountered exception while handling in channel with name "identity:use_ability"
java.lang.NoSuchMethodError: net.minecraft.class_1670.<init>(Lnet/minecraft/class_1937;DDDDDD)V
at draylar.identity.ability.impl.EnderDragonAbility.onUse(EnderDragonAbility.java:23) ~[identity-1.11.3-beta-1.16.4.jar:?]
at draylar.identity.ability.impl.EnderDragonAbility.onUse(EnderDragonAbility.java:12) ~[identity-1.11.3-beta-1.16.4.jar:?]
at draylar.identity.network.ServerNetworking.lambda$registerUseAbilityPacketHandler$0(ServerNetworking.java:35) ~[identity-1.11.3-beta-1.16.4.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[86325d3d-e591-4603-ae97-2ef974b3d9e5.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[86325d3d-e591-4603-ae97-2ef974b3d9e5.jar:?]
at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [86325d3d-e591-4603-ae97-2ef974b3d9e5.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [86325d3d-e591-4603-ae97-2ef974b3d9e5.jar:?]
at net.minecraft.class_3244.handler$zcp000$handleCustomPayloadReceivedAsync(class_3244.java:1666) [intermediary-server.jar:?]
at net.minecraft.class_3244.method_12075(class_3244.java) [intermediary-server.jar:?]
at net.minecraft.class_2817.method_12199(class_2817.java:44) [intermediary-server.jar:?]
at net.minecraft.class_2817.method_11054(class_2817.java:9) [intermediary-server.jar:?]
at net.minecraft.class_2535.method_10759(class_2535.java:156) [intermediary-server.jar:?]
at net.minecraft.class_2535.method_10770(class_2535.java:147) [intermediary-server.jar:?]
at net.minecraft.class_2535.channelRead0(class_2535.java:52) [intermediary-server.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [intermediary-server.jar:?]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [intermediary-server.jar:?]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [intermediary-server.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [intermediary-server.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[16:57:03] [Server thread/INFO]: PufflePup lost connection: Internal Exception: java.lang.NoSuchMethodError: net.minecraft.class_1670.<init>(Lnet/minecraft/class_1937;DDDDDD)V
[16:57:03] [Server thread/INFO]: PufflePup left the game`

**Comment by ghost** [comment]
Sorry but how exactly do you write text like that?

**Comment by PufflePup** [comment]
<details>

<summary> Logs </summary>



</details>

**Comment by James103** [comment]
Did you mean to actually copy-paste in the actual logs (instead of leaving it blank)?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
Sorry about this I literally just made a GitHub account as I wanted to report this so I have little knowledge about these kind of things.

**Comment by PufflePup** [comment]
<details>

<summary> test </summary>



</details>

**Comment by James103** [comment]
Try to strip the `<!-- -->` surrounding the logs you pasted in.

**Comment by ghost** [comment]
<details>

<summary> Logs </summary>

[17:06:06] [Netty Epoll Server IO #3/ERROR]: Encountered exception while handling in channel with name "identity:use_ability"
java.lang.NoSuchMethodError: net.minecraft.class_1670.<init>(Lnet/minecraft/class_1937;DDDDDD)V
at draylar.identity.ability.impl.EnderDragonAbility.onUse(EnderDragonAbility.java:23) ~[identity-1.11.3-beta-1.16.4.jar:?]
at draylar.identity.ability.impl.EnderDragonAbility.onUse(EnderDragonAbility.java:12) ~[identity-1.11.3-beta-1.16.4.jar:?]
at draylar.identity.network.ServerNetworking.lambda$registerUseAbilityPacketHandler$0(ServerNetworking.java:35) ~[identity-1.11.3-beta-1.16.4.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[86325d3d-e591-4603-ae97-2ef974b3d9e5.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[86325d3d-e591-4603-ae97-2ef974b3d9e5.jar:?]
at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [86325d3d-e591-4603-ae97-2ef974b3d9e5.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [86325d3d-e591-4603-ae97-2ef974b3d9e5.jar:?]
at net.minecraft.class_3244.handler$zcp000$handleCustomPayloadReceivedAsync(class_3244.java:1666) [intermediary-server.jar:?]
at net.minecraft.class_3244.method_12075(class_3244.java) [intermediary-server.jar:?]
at net.minecraft.class_2817.method_12199(class_2817.java:44) [intermediary-server.jar:?]
at net.minecraft.class_2817.method_11054(class_2817.java:9) [intermediary-server.jar:?]
at net.minecraft.class_2535.method_10759(class_2535.java:156) [intermediary-server.jar:?]
at net.minecraft.class_2535.method_10770(class_2535.java:147) [intermediary-server.jar:?]
at net.minecraft.class_2535.channelRead0(class_2535.java:52) [intermediary-server.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [intermediary-server.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [intermediary-server.jar:?]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [intermediary-server.jar:?]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [intermediary-server.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [intermediary-server.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[17:06:06] [Server thread/INFO]: PufflePup lost connection: Internal Exception: java.lang.NoSuchMethodError: net.minecraft.class_1670.<init>(Lnet/minecraft/class_1937;DDDDDD)V

</details>

**Comment by ghost** [comment]
These are the logs that come up when it crashes me.

**Comment by Draylar** [comment]
[1.11.4](https://www.curseforge.com/minecraft/mc-mods/identity/files/3177925) (yesterday's patch release) fixed this issue :) 

feel free to re-open the issue if you encounter it again, thanks for the report 👍
