### ISSUE TITLE
Crash with Pehkui and/or new Fabric API

### ISSUE THREAD

**Issue by M3lonKing** [Draylar/identity#203]
Whenever I try to load up a world the game crashes.

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here?

**Comment by lieuweberg** [comment]
<details>
<summary>I have the same issue. Click the arrow for the crash report.</summary>

```
    ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 08/05/21 20:16
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Could not initialize class draylar.identity.registry.Components
	at net.minecraft.class_1657.method_18378(class_1657.java:5473)
	at net.minecraft.class_1297.<init>(class_1297.java:262)
	at net.minecraft.class_1309.<init>(class_1309.java:219)
	at net.minecraft.class_1657.<init>(class_1657.java:199)
	at net.minecraft.class_3222.<init>(class_3222.java:185)
	at net.minecraft.class_3324.method_14613(class_3324.java:461)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$zkh000$handlePlayerJoin(class_3248.java:562)
	at net.minecraft.class_3248.method_18785(class_3248.java:65)
	at net.minecraft.class_2535.method_10754(class_2535.java:228)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4963/2049150559.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1271908824 bytes (1212 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.14
		fabric: Fabric API 0.34.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.2+d6244c6d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		identity: Identity 1.13.1-1.16.5
		io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.8.2
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		omega-config: OmegaConfig 1.0.4
		origins: Origins 0.7.1
		pehkui: Pehkui 2.1.0+21w18a
		playerabilitylib: Pal 1.2.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods, file/dragonite_origin_og.zip, file/steampunkV1.zip
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

```
</details>
I also get a crash on 1.13.0 and 1.12.0. I assume it's an issue to do with a newer fabric version since else this would've been reported earlier than today.

**Comment by Draylar** [comment]
1. If you are on Fabric API 34, update to Identity 1.13.1
2. If you are using Pehkui, [use this updated Pehkui jar](https://github.com/Draylar/identity/issues/202#issuecomment-834783629) until an official release jar is published (fix has been PRed and accepted). This is the issue in any log that mentions `Could not initialize class draylar.identity.registry.Components`.

**Comment by James103** [comment]
Last update to Pekhui mod is 2.2.1, released on June 14, 2021 (5 weeks since this issue was closed). Fabric API 0.34.x is discontinued since June 10, 2021, with the most recent overall update being 0.36.0, released on June 20, 2021. Is this issue still worth keeping pinned?
