### ISSUE TITLE
Identity UI not showing Entity icons in 1.4.0-beta

### ISSUE THREAD

**Issue by sean-work** [Draylar/identity#26]
It looks like this:

![image](https://user-images.githubusercontent.com/68880081/88696938-ca711a00-d0fb-11ea-8e19-82c2374341df.png)

Great mod by the way, even used the config to balance to prevent overpowered gameplay on my server. Using it mostly for pranks. Thanks.

Here's my log:

`[17:53:24] [main/FATAL]: Error executing task on Client
net.minecraft.class_148: Loading entity NBT
	at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.20) ~[?:?]
	at net.minecraft.entity.Entity.fromTag(Entity:1645) ~[?:?]
	at draylar.identity.cca.IdentityComponent.fromTag(IdentityComponent.java:111) ~[identity-1.4.0-beta-1.16.jar:?]
	at nerdhub.cardinal.components.api.util.sync.BaseSyncedComponent.readFromPacket(BaseSyncedComponent.java:69) ~[2836e3aa-5461-4b33-a489-ffc688d4b29c.jar:?]
	at nerdhub.cardinal.components.api.util.sync.EntitySyncedComponent.processPacket(EntitySyncedComponent.java:96) ~[49ebf1a1-8367-4122-a29a-43e016bf93a9.jar:?]
	at nerdhub.cardinal.components.CardinalComponentsEntity.lambda$null$5(CardinalComponentsEntity.java:84) ~[49ebf1a1-8367-4122-a29a-43e016bf93a9.jar:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at nerdhub.cardinal.components.CardinalComponentsEntity.lambda$null$6(CardinalComponentsEntity.java:84) ~[49ebf1a1-8367-4122-a29a-43e016bf93a9.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:988) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:654) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_638 cannot be cast to class net.minecraft.class_3218 (net.minecraft.class_638 and net.minecraft.class_3218 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @57a3e26a)
	at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.20) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity.readCustomDataFromTag(BeeEntity:260) ~[?:?]
	at net.minecraft.entity.Entity.fromTag(Entity:1636) ~[?:?]
	... 28 more`

**Comment by James103** [comment]
Are you using All of Fabric for 1.16? If so, you may be running to a similar problem as shown in #25.

**Comment by sean-work** [comment]
Not explicitly, i did start off with that as a base, but i've been changing my mods list over the past month and only encountered the issue the past couple of days (I have been adding mods), and sorry, saw the other thread title but it didn't indicate the same issue.

If I run it in an instance by itself, it does of course work, so definitely one of my mods conflicting.

Here's my modlist:
![image](https://user-images.githubusercontent.com/68880081/88697976-58013980-d0fd-11ea-9640-4a2a85790bf3.png)

**Comment by sean-work** [comment]
Got it to work again, it's one of these (not antique atlas, that was already disabled, i was using voxelmap)
![image](https://user-images.githubusercontent.com/68880081/88699986-ed9dc880-d0ff-11ea-8c92-c28578ecf7cb.png)
Will try to narrow down when i get time. MultiMC log actually reads the same despite not having UI problems anymore.

**Comment by sean-work** [comment]
Okay, it's [Chest Tracker](https://www.curseforge.com/minecraft/mc-mods/chest-tracker/) which causes the UI glitch, it's not in the All of Fabric 3 pack for 1.16, but two of it's embedded jars "cloth-client-events-v0-1.0.6.jar" and spinnery-3.0.56+fabric-1.16.x.jar are in that modpack. So I imagine it must be one of those. (the third embedded jar is "autoconfig1u-3.2.0-unstable.jar" just for full info)

**Comment by Draylar** [comment]
Not entirely sure what is causing this (I can't reproduce it), but I just updated _all_ the project deps in 1.5.0-beta (assuming it was a Spinnery issue). Can you tell me if you still see this issue in 1.5.0-beta?

**Comment by sean-work** [comment]
The issue is now fixed, thanks a lot!
![2020-07-31_22 43 52](https://i.imgur.com/MXyMX3C.png)
