### ISSUE TITLE
Crashes in certain conditions around other mobs (Forge 1.17.1)

### ISSUE THREAD

**Issue by N30N-N1NJ4** [Draylar/identity#308]
The mod runs as it should but there's a weird issue of the game crashing when I'm using an item like food or a shield when in conflict or in close quarters with another mob.
For example, I was in combat with a skeleton and tried using my shield but the game immediately crashed, the error message it gave was this:

**java.lang.NoSuchMethodError: 'void draylar.identity.api.platform.forge.PlayerHostilityImpl.set(net.minecraft.world.entity.player.Player, int)'
	at draylar.identity.api.platform.PlayerHostility.set(PlayerHostility.java) ~[identity-forge-2.0.0-1.17.1.jar%2360!:?] {re:mixin,re:classloading}
	at draylar.identity.registry.EventHandlers.lambda$registerHostilityUpdateHandler$0(EventHandlers.java:16) ~[identity-forge-2.0.0-1.17.1.jar%2360!:?] {re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?] {re:mixin}
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:54) ~[architectury-2.6.35.jar%2356!:?] {re:classloading}
	at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:82) ~[architectury-2.6.35.jar%2356!:?] {re:classloading}
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84) ~[guava-21.0.jar%2320!:?] {}
	at jdk.proxy3.$Proxy72.interact(Unknown Source) ~[?:?] {}
	at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:343) ~[architectury-2.6.35.jar%2356!:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_90_EventHandlerImplCommon_event_EntityInteract.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:733) ~[forge-1.17.1-37.0.109-universal.jar%2372!:?] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_36157_(Player.java:951) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:3dskinlayers.mixins.json:PlayerMixin,pl:mixin:APP:identity-forge.mixins.json:PlayerEntityDataMixin,pl:mixin:APP:identity-forge.mixins.json:PlayerEntityTickMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_143678_(ServerGamePacketListenerImpl.java:1204) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_142299_(ServerGamePacketListenerImpl.java:1216) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.m_142457_(SourceFile:116) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(SourceFile:66) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerGamePacketListenerImpl.java:1201) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(SourceFile:53) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(SourceFile:13) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.lambda$checkThreadAndEnqueue$0(PacketUtils.java:38) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[OptiFine_1.17.1_HD_U_H1.jar%2373!:?] {re:classloading}
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:193) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(SourceFile:23) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:775) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:158) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:752) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:171) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:738) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:687) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.17.1-20210706.113038-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}**
	
The mods I'm using are these:
![image](https://user-images.githubusercontent.com/87194806/142728366-38333602-79d3-4a79-9538-ec1bdbf95b66.png)

**Comment by Draylar** [comment]
Fixed in 2.1.0 alpha for Forge - let me know if you end up using it and how it plays out. Thank you for the detailed report! :)
