### ISSUE TITLE
Server crashes if I give a zombie villager a golden apple 

### ISSUE THREAD

**Issue by 0nlyRich** [Draylar/identity#311]
like I said the Server crashes if I give a zombie villager a golden apple... 
Exception caught during firing event: 'void draylar.identity.api.platform.forge.PlayerHostilityImpl.set(net.minecraft.world.entity.player.Player, int)

**Comment by 0nlyRich** [comment]
if you block damage with a shield the server crashes as well...

**Comment by James103** [comment]
Do you have the full crash log?

**Comment by 0nlyRich** [comment]
Exception caught during firing event: 'void draylar.identity.api.platform.forge.PlayerHostilityImpl.set(net.minecraft.world.entity.player.Player, int)'
        Index: 1
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                2: NORMAL
                3: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@73011087 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
java.lang.NoSuchMethodError: 'void draylar.identity.api.platform.forge.PlayerHostilityImpl.set(net.minecraft.world.entity.player.Player, int)'
        at TRANSFORMER/identity@2.0.0-1.17.1/draylar.identity.api.platform.PlayerHostility.set(PlayerHostility.java)
        at TRANSFORMER/identity@2.0.0-1.17.1/draylar.identity.registry.EventHandlers.lambda$registerHostilityUpdateHandler$0(EventHandlers.java:16)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at TRANSFORMER/architectury@2.6.35/dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:54)
        at TRANSFORMER/architectury@2.6.35/dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:82)
        at MC-BOOTSTRAP/guava@21.0/com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
        at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy55.interact(Unknown Source)
        at TRANSFORMER/architectury@2.6.35/dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:343)
        at net.minecraftforge.eventbus.ASMEventHandler_31_EventHandlerImplCommon_event_EntityInteract.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@37.0.104/net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:733)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.world.entity.player.Player.m_36157_(Player.java:951)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_143678_(ServerGamePacketListenerImpl.java:1204)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_142299_(ServerGamePacketListenerImpl.java:1216)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.m_142457_(SourceFile:116)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(SourceFile:66)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerGamePacketListenerImpl.java:1201)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(SourceFile:53)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(SourceFile:13)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.protocol.PacketUtils.m_131356_(SourceFile:21)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.TickTask.run(SourceFile:18)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(SourceFile:151)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(SourceFile:23)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:775)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(SourceFile:125)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:752)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(SourceFile:134)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:738)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:687)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
        at java.base/java.lang.Thread.run(Thread.java:833)

[19:05:09] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void draylar.identity.api.platform.forge.PlayerHostilityImpl.set(net.minecraft.world.entity.player.Player, int)'
        at draylar.identity.api.platform.PlayerHostility.set(PlayerHostility.java) ~[identity-forge-2.0.0-1.17.1.jar%2326!:?]
        at draylar.identity.registry.EventHandlers.lambda$registerHostilityUpdateHandler$0(EventHandlers.java:16) ~[identity-forge-2.0.0-1.17.1.jar%2326!:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:54) ~[architectury-2.6.35.jar%2324!:?]
        at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:82) ~[architectury-2.6.35.jar%2324!:?]
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84) ~[guava-21.0.jar%2320!:?]
        at jdk.proxy3.$Proxy55.interact(Unknown Source) ~[?:?]
        at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:343) ~[architectury-2.6.35.jar%2324!:?]
        at net.minecraftforge.eventbus.ASMEventHandler_31_EventHandlerImplCommon_event_EntityInteract.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:733) ~[forge-1.17.1-37.0.104-universal.jar%2335!:?]
        at net.minecraft.world.entity.player.Player.m_36157_(Player.java:951) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_143678_(ServerGamePacketListenerImpl.java:1204) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_142299_(ServerGamePacketListenerImpl.java:1216) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.m_142457_(SourceFile:116) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(SourceFile:66) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerGamePacketListenerImpl.java:1201) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(SourceFile:53) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(SourceFile:13) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(SourceFile:21) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(SourceFile:151) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(SourceFile:23) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:775) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(SourceFile:125) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:752) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(SourceFile:134) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:738) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:687) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%2331!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Draylar** [comment]
Fixed in 2.1.0 alpha for Forge, thanks for the report!
