### ISSUE TITLE
identity mod not working multiplayer

### ISSUE THREAD

**Issue by DogeTOM1143** [Draylar/identity#398]
hello can someone help me the mod is not working in multiplayer

**Comment by James103** [comment]
The same version of the mod must be installed on both the server and client to work properly.

**Comment by DogeTOM1143** [comment]
well i am usin fabric with the api thingy and im on 1.19

**Comment by Natedogwoooof** [comment]
same

**Comment by Nazerillo** [comment]
I'm going to take advantage of this issue. I'm having the same error. I'm having another error trying to join a singleplayer world. Server crashes using the next version and mods:

- fabric-server-mc.1.19.1-loader.0.14.8-launcher.0.11.0.jar
- fabric-api-0.58.5+1.19.1.jar
- architectury-6.0.34-fabric.jar
- identity-2.5.0-1.19-fabric.jar

> [20:54:28] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[20:54:29] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.AbstractMethodError: Receiver class draylar.identity.command.IdentityCommand$$Lambda$3272/0x00000008013f11f8 does not define or inherit an implementation of the resolved method 'abstract void register(com.mojang.brigadier.CommandDispatcher, net.minecraft.class_7157, net.minecraft.class_2170$class_5364)' of interface dev.architectury.event.events.common.CommandRegistrationEvent.
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.1-loader.0.14.8-launcher.0.11.0.jar:0.11.0]
Caused by: java.lang.AbstractMethodError: Receiver class draylar.identity.command.IdentityCommand$$Lambda$3272/0x00000008013f11f8 does not define or inherit an implementation of the resolved method 'abstract void register(com.mojang.brigadier.CommandDispatcher, net.minecraft.class_7157, net.minecraft.class_2170$class_5364)' of interface dev.architectury.event.events.common.CommandRegistrationEvent.
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$18(EventHandlerImpl.java:77) ~[architectury-6.0.34-fabric.jar:?]
	at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43) ~[fabric-command-api-v2-2.1.5+0c17ea9695-b5c51f41338a42a0.jar:?]
	at net.minecraft.class_2170.handler$zci000$fabric_addCommands(class_2170.java:1048) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:251) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:84) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_6904.method_40431(class_6904.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:158) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:952) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:946) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 4 more

**Comment by baileyholl** [comment]
Confirmed on forge with crash above with
[Forge 1.19.1] v6.0.34 Architectuary 
Identity 2.5.0

**Comment by Natedogwoooof** [comment]
For me the World Doesn't show up at all

**Comment by Natedogwoooof** [comment]
And i tryed unblocking the firewall direct connect and we have the same mods its weard
