### ISSUE TITLE
crashes when i open the morph menu

### ISSUE THREAD

**Issue by Pichupeh** [Draylar/identity#403]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/28/22, 9:51 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: Index 103 out of bounds for length 21
	at draylar.identity.impl.variant.AxolotlTypeProvider.modifyText(AxolotlTypeProvider.java:37)
	at draylar.identity.impl.variant.AxolotlTypeProvider.modifyText(AxolotlTypeProvider.java:11)
	at draylar.identity.api.variant.IdentityType.createTooltipText(IdentityType.java:159)
	at draylar.identity.screen.widget.EntityWidget.method_25352(EntityWidget.java:129)
	at draylar.identity.screen.IdentityScreen.method_25394(IdentityScreen.java:122)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at draylar.identity.impl.variant.AxolotlTypeProvider.modifyText(AxolotlTypeProvider.java:37)
	at draylar.identity.impl.variant.AxolotlTypeProvider.modifyText(AxolotlTypeProvider.java:11)
	at draylar.identity.api.variant.IdentityType.createTooltipText(IdentityType.java:159)
	at draylar.identity.screen.widget.EntityWidget.method_25352(EntityWidget.java:129)
	at draylar.identity.screen.IdentityScreen.method_25394(IdentityScreen.java:122)

-- Screen render details --
Details:
	Screen name: draylar.identity.screen.IdentityScreen
	Mouse location: Scaled: (240, 135). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Pichupeh'/338, l='ClientLevel', x=-59.45, y=5.09, z=116.54]]
	Chunk stats: 1024, 615
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,4,0), Section: (at 0,4,0 in -9,0,0; chunk contains blocks -144,-64,0 to -129,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 327559 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Rainbow GUI, Sword Sounds Resources V.1.2, Technoblade Pig, Faithful+64x, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1001322128 bytes (954 MiB) / 4194304000 bytes (4000 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9415
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a0
	Graphics card #1 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31552.30
	Virtual memory used (MB): 28196.01
	Swap memory total (MB): 15405.00
	Swap memory used (MB): 1975.80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19
		architectury: Architectury 5.9.31
		badpackets: Bad Packets 0.1.2
		campchair: Camp Chair 1.0.2
		cloth-config: Cloth Config v6 7.0.73
			cloth-basic-math: cloth-basic-math 0.6.1
		deathknell: DeathKnell 4.0.1
		dualwielding: Dual Wielding 1.1.2
		duckling: Duckling 2.0.3
		effective: Effective 1.2.2
		escaperope: Escape Rope 2.0.1
		eyemod: EyeMod 2.0
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		geckolib3: Geckolib 3.1.0
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		glassdoor: Glass Doors 2.1.0+1.18
		glowingbanners: Glow Banners 1.2.0
		identity: Identity 2.5.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		immersive_paintings: Immersive Paintings 0.1.5+1.19
		instantblocks: Instant Blocks 1.6.3
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		libraryferret: Library Ferret 2.0.0
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		minecraft: Minecraft 1.19
		mobscarecrow: Mob Scarecrow 2.2.1
		modmenu: Mod Menu 4.0.4
		more-axolotls: More Axolotls 1.0.2
		mtr: Minecraft Transit Railway 1.19-3.0.1
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		replaymod: Replay Mod 1.19-2.6.6
		roughlyenoughitems: Roughly Enough Items 9.1.517
		sculkhornid: Sculk Horn Mod 0.1.3
		simply_houses: Simply Houses 1.1.2-1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		t_and_t: Towns and Towers - Structure Add-on 1.8
		universal-graves: Universal Graves 2.1.0+1.19
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.6+1.19
			polymer: Polymer (Core) 0.2.2+1.19
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.1+1.19
		wardentools: Warden Tools 1.0
		weaponmaster: YDM's Weapon Master 3.0.0
		weird_equipment: Weird Equipment 0.8-beta
		worldedit: WorldEdit 7.2.11-beta-01+6200-0877589
		wthit: wthit 5.8.0
		wurst: Wurst Client v7.27-MC1.19
		xaerobetterpvp: Better PVP Mod 22.12.0
	Loaded Shaderpack: BSL_v8.1.03.zip
		Profile: HIGH (+0 options changed by user)
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Rainbow GUI (incompatible), file/Sword Sounds Resources V.1.2 (incompatible), file/Technoblade Pig, file/Faithful+64x
	Current Language: English (US)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Pichupeh'/338, l='ServerLevel[OL TACO]', x=-59.45, y=5.09, z=116.54]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental\

**Comment by MandieLandie** [comment]
I got the same error, I think it has something to do with the 'More Axolotls' mod, I'm not sure how to solve it though.
