### ISSUE TITLE
Game crashing when trying to create or load the world

### ISSUE THREAD

**Issue by Danielmarl** [Draylar/identity#404]
My Game Kept Crashing if I tried to load or create the world. I'm In 1.19.1 forge 
**Game log:**
*[Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.](https://www.toptal.com/developers/hastebin/kurimatide.yaml)*

**Comment by karl134** [comment]
I have the same

**Comment by Danielmarl** [comment]
Crash Report

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2022-08-01 11:03:55
Description: mouseClicked event handler

java.lang.AbstractMethodError: Receiver class draylar.identity.command.IdentityCommand$$Lambda$3644/0x00000001009fe3b8 does not define or inherit an implementation of the resolved method 'abstract void register(com.mojang.brigadier.CommandDispatcher, net.minecraft.class_7157, net.minecraft.class_2170$class_5364)' of interface dev.architectury.event.events.common.CommandRegistrationEvent.
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$18(EventHandlerImpl.java:77)
	at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43)
	at net.minecraft.class_2170.handler$zdk000$fabric_addCommands(class_2170.java:1048)
	at net.minecraft.class_2170.<init>(class_2170.java:251)
	at net.minecraft.class_5350.<init>(class_5350.java:46)
	at net.minecraft.class_5350.method_29466(class_5350.java:84)
	at net.minecraft.class_7237.method_42098(class_7237.java:28)
	at net.minecraft.class_525.method_31130(class_525.java:144)
	at net.minecraft.class_528.method_43462(class_528.java:147)
	at net.minecraft.class_528.<init>(class_528.java:91)
	at net.minecraft.class_526.method_25426(class_526.java:65)
	at net.minecraft.class_437.method_41843(class_437.java:389)
	at net.minecraft.class_437.method_25423(class_437.java:380)
	at net.minecraft.class_310.method_1507(class_310.java:1034)
	at net.minecraft.class_442.method_19861(class_442.java:160)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:343)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1207)
	at net.minecraft.class_310.method_1514(class_310.java:767)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$18(EventHandlerImpl.java:77)
	at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43)
	at net.minecraft.class_2170.handler$zdk000$fabric_addCommands(class_2170.java:1048)
	at net.minecraft.class_2170.<init>(class_2170.java:251)
	at net.minecraft.class_5350.<init>(class_5350.java:46)
	at net.minecraft.class_5350.method_29466(class_5350.java:84)
	at net.minecraft.class_7237.method_42098(class_7237.java:28)
	at net.minecraft.class_525.method_31130(class_525.java:144)
	at net.minecraft.class_528.method_43462(class_528.java:147)
	at net.minecraft.class_528.<init>(class_528.java:91)
	at net.minecraft.class_526.method_25426(class_526.java:65)
	at net.minecraft.class_437.method_41843(class_437.java:389)
	at net.minecraft.class_437.method_25423(class_437.java:380)
	at net.minecraft.class_310.method_1507(class_310.java:1034)
	at net.minecraft.class_442.method_19861(class_442.java:160)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:343)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1207)
	at net.minecraft.class_310.method_1514(class_310.java:767)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2345)
	at net.minecraft.class_310.method_1514(class_310.java:786)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 659400480 bytes (628 MiB) / 1543503872 bytes (1472 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.21
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1be1
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5751
	Graphics card #1 name: Citrix Indirect Display Adapter
	Graphics card #1 vendor: Citrix Systems Inc. (0x5853)
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: 0x1003
	Graphics card #1 versionInfo: DriverVersion=12.40.44.247
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37552.42
	Virtual memory used (MB): 9922.28
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 4.42
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 6.0.35
		fabric: Fabric API 0.58.5+1.19.1
			fabric-api-base: Fabric API Base 0.4.9+e62f51a395
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f4095
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.15+d5533c0195
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f4095
			fabric-command-api-v1: Fabric Command API (v1) 1.2.9+f71b366f95
			fabric-command-api-v2: Fabric Command API (v2) 2.1.5+0c17ea9695
			fabric-commands-v0: Fabric Commands (v0) 0.2.26+df3654b395
			fabric-containers-v0: Fabric Containers (v0) 0.1.31+df3654b395
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213e95
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d2495
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4a95
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.5+a680b9b495
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f78595
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f4095
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f4095
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b395
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+1899036195
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c4395
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f4095
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f4095
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b395
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc73895
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e56895
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c695
			fabric-message-api-v1: Fabric Message API (v1) 5.0.1+4e0178f495
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc73895
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f4095
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.1+3082331495
			fabric-networking-v0: Fabric Networking (v0) 0.3.18+df3654b395
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f4095
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553a95
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.21+23c4cfef95
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f4095
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39f95
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b395
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f4095
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f4095
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b395
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f4095
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a395
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e095
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effaf95
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.10+9ff28f4095
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f4095
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a395
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c695
		fabricloader: Fabric Loader 0.14.8
		identity: Identity 2.5.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.1
	Launched Version: fabric-loader-0.14.8-1.19.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.51, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by sashaironfist** [comment]
same

**Comment by Draylar** [comment]
Issue has been fixed, thanks!
