### ISSUE TITLE
[1.18.2] Game Crashes Instantly when game boots up. 

### ISSUE THREAD

**Issue by ItsSnowia** [Draylar/identity#452]
So I am using Identity 2.3.0 1.18.2 Fabric,
(identity-2.3.0-1.18.2-fabric.jar) 
but the game crashes instantly when I boot it up, is there something I am missing here for key information?
Like any possible mod conflicts or something else or is it the mod it self that's causing issues..?

Minor Part of the crash report:
`java.lang.RuntimeException: Mixin transformation of net.minecraft.class_898 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.<init>(class_310.java:557)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 9 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [identity.mixins.json:ShadowMixin from mod identity] from phase [DEFAULT] in config [identity.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/class_898::adjustShadowSize was removed by another injector [INJECT Applicator Phase -> identity.mixins.json:ShadowMixin from mod identity -> Apply Injections ->  -> Inject -> identity.mixins.json:ShadowMixin from mod identity->@ModifyVariable::adjustShadowSize(F)F]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:169)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 12 more
`

Full Crash log:
[https://pastebin.com/zcDqv9db](url)
File Verison (Just Incase): 
[crash-2022-09-27_04.36.29-client.txt](https://github.com/Draylar/identity/files/9653829/crash-2022-09-27_04.36.29-client.txt)

**Comment by ItsSnowia** [comment]
Update: So I went through my mods list and put one mod after another back in one at an time, and I might have the answer already to this crash report, from my discovery, First Person Model Mod by tr9zw has been causing the issue as after I had place it back in and then removed it but then put back the mods from before, basically all the mods I had but minus First Person it booted up just fine, so I basically just solved my own issue report! Well then 😅...  I'll close this issue ticket but will update via new one if any other issues pop up.
(https://www.curseforge.com/minecraft/mc-mods/first-person-model)
