### ISSUE TITLE
"Player ability minecraft:mayfly was updated externally (expected disabled, was enabled)" spam -> Problem with staying in flight?

### ISSUE THREAD

**Issue by Fabrieze** [Draylar/identity#536]
I REALLY wish I had more information on this, but some, not all, players on my server are having an issue staying in flight with identity.

Example:
They turn into bee, fly up, but eating, using tools, and otherwise interacting with anything causes them to fall out of the air.
I haven't been able to replicate it on my client, but the console IS giving this same error repeatedly: 

`[01.06 02:27:36] [Server] [Server thread/WARN]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
[01.06 02:27:36] [Server] java.lang.RuntimeExceptionstacktrace
[01.06 02:27:36] [Server] 	at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:63) ~[playerabilitylib-1.6.0-37dc33edd6b65e6c.jar:?]
[01.06 02:27:36] [Server] 	at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[playerabilitylib-1.6.0-37dc33edd6b65e6c.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_3222.handler$efi000$playerabilitylib$checkAbilityConsistency(class_3222.java:15343) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_3222.method_7355(class_3222.java:1296) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_2985.handler$dad000$identity$refreshFlight(class_2985.java:2528) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_2985.method_12878(class_2985.java:205) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_179$class_180.method_796(class_179.java:35) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_4558.method_22510(class_4558.java:74) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_2066.method_24362(class_2066.java:55) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_2066.method_8950(class_2066.java:51) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_3222$2.method_7635(class_3222.java:244) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_1703.method_34246(class_1703.java:218) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_1703.method_7623(class_1703.java:175) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_3222.method_5773(class_3222.java:449) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_3218.method_18762(class_3218.java:712) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_1937.method_18472(class_1937.java:466) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_3218.method_31420(class_3218.java:371) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.server.MinecraftServer.handler$bij000$carpet$modifiedRunLoop(MinecraftServer.java:6385) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
[01.06 02:27:36] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]`

Any ideas, at all, as to what is going on? And if not for the flight thing, any insight onto the console spam for player abilities: mayfly?

**Comment by James103** [comment]
What other mods are you running on the server at the time the flight broke?

**Comment by Fabrieze** [comment]
Oh, boy. There is... a lot.

Here's the whole list from my mods folder. This isn't an issue with every player on my server, so I thought I'd shoot my shot here. I understand if you have no further information because of MY lack of information. I'll do further investigation later by maybe remotely accessing my friend's PC, see what's up. It's a consistent issue where they turn into a bee, interact with something in some way, and then get thrown out of flight mode.

AdditionalStructures-1.19.x-(v.4.1.1).jar
Adorn-3.8.3+1.19.2-fabric.jar
adventurez-1.4.18.jar
another_furniture-fabric-2.1.2-1.19.2.jar
arcanus-1.30.jar
architectury-6.5.82-fabric.jar
artifacts-7.1.1+fabric.jar
badpackets-fabric-0.2.1.jar
bclib-2.1.6.jar
BeaconOverhaul-1.7.3+1.19.2.jar
better-end-2.1.4.jar
BetterAnimationsCollection-v4.0.5-1.19.2-Fabric.jar
c2me-fabric-mc1.19.2-0.2.0+alpha.9.9.jar
carpet-fixes-1.19-1.12.2.jar
carryon-fabric-1.19.2-2.0.5.11.jar
cave-enhancements-1.19.2-2.1.12-fabric.jar
charm-fabric-1.19.2-4.4.4.jar
charmofundying-fabric-6.2.0+1.19.2.jar
cloth-config-8.2.88-fabric.jar
Cobblemon-fabric-1.3.2+1.19.2.jar
compact_storage_fabric-5.0.3_1.19.2.jar
consistency_plus-fabric-0.5.1+1.19.2.jar
Controlling-fabric-1.19.2-10.0+7.jar
CorgiLib-fabric-1.19.2-1.0.0.32.jar
crawl-0.11.1.jar
customizableelytra-fabric-1.6.4-1.19.jar
dark-enchanting-1.0.2+1.19.2.jar
dawn-3.5.0.jar
DiagonalFences-v4.2.4-1.19.2-Fabric.jar
dungeons-and-taverns-2.0.2.jar
dynamic-fps-2.2.0.jar
EasyAnvils-v4.0.11-1.19.2-Fabric.jar
EasyMagic-v4.3.3-1.19.2-Fabric.jar
lytraslot-fabric-6.1.1+1.19.2.jar
emotecraft-for-MC1.19.2-2.2.7-b.build.48-fabric.jar
enhancedblockentities-0.7.2+1.19.2.jar
entityculling-fabric-1.6.1-mc1.19.2.jar
exlinefurniture-fabric-1.19.2-v2.3.2.jar
exordium-fabric-1.0.2-mc1.19.2.jar
extraorigins-1.19-2.jar
fabric-api-0.76.0+1.19.2.jar
fabric-carpet-1.19.2-1.4.84+v221018.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
FallingTree-1.19.2-3.10.0.jar
Fastload+1.18.2-1.20-3.4.0.jar
Female-Gender-Mod-fabric-1.19.2-3.0.1.jar
ferritecore-5.0.3-fabric.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
FpsReducer2-fabric-1.19.2-2.1.jar
friendsandfoes-fabric-mc1.19.2-1.8.2.jar
fungal-mage-V2.9.6.jar
Galosphere-1.19.2-1.2.2-Fabric.jar
geckolib-fabric-1.19-3.1.40.jar
handcrafted-fabric-1.19.2-2.0.6.jar
identity-2.6.1-1.19.1-fabric.jar
ImmediatelyFast-1.1.12+1.19.jar
indium-1.0.9+mc1.19.2.jar
iris-mc1.19.2-1.6.2.jar
jei-1.19.2-fabric-11.6.0.1015.jar
krypton-0.2.1.jar
 lambdynamiclights-2.2.0+1.19.2.jar
 lazydfu-0.1.3.jar
 LeavesBeGone-v4.0.1-1.19.2-Fabric.jar
lithium-fabric-mc1.19.2-0.11.1.jar
lootr-1.19-0.4.25.64.jar
 mcw-doors-1.0.9fabric-mc1.19.2.jar
 mcw-trapdoors-1.0.9-mc1.19.2fabric.jar
mcw-windows-2.1.2-mc1.19.2fabric.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
mermod-fabric-2.21.jar
midnightlib-fabric-1.0.0.jar
mixintrace-1.1.1+1.17.jar
modmenu-4.2.0-beta.2.jar
moonlight-1.19.2-2.2.33-fabric.jar
moreculling-1.19.1-0.17.0.jar
mostructures-1.4.3+1.19.2.jar
mousewheelie-1.10.7+mc1.19.2.jar
mythic-mounts-1.19.2-7.2.jar
NaturesCompass-1.19.2-2.1.0-fabric.jar
NoChatReports-FABRIC-1.19.2-v1.13.12.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.1.jar
Origins-1.19.2-1.7.1.jar
Origins-Classes-1.19-1.4.0.jar
Origins-Vampire-fabric-quilt-v2.1.0.jar
originsumbrellas-1.5.4.jar
owo-lib-0.9.3+1.19.jar
Patchouli-1.19.2-77-FABRIC.jar
Pehkui-3.7.3+1.14.4-1.20.jar
player-animation-lib-fabric-1.0.2.jar
polymorph-fabric-0.46.1+1.19.2.jar
promenade-2.7.1.jar
PuzzlesLib-v4.4.0-1.19.2-Fabric.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
repurposed_structures_fabric-6.3.24+1.19.2.jar
resourcefullib-fabric-1.19.2-1.1.24.jar
show-me-your-skin-1.6.3+1.19.2.jar
simplehats-fabric-1.19.2-0.1.6.jar
smallships-fabric-1.19.X-2.0.0a1.1.1.jar
smarterfarmers-1.19.2-1.7.2-fabric.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
stack-to-nearby-chests-mc1.19.2-0.2.7.jar
starlight-1.1.1+fabric.ae22326.jar
supplementaries-1.19.2-2.3.11-fabric.jar
TerraBlender-fabric-1.19.2-2.0.1.136.jar
toofast-1.19-1.0.0.jar
tooltipfix-1.1.1-1.19.jar
Towns-and-Towers-v.1.10.1-FABRIC-1.19.2.jar
trade-cycling-fabric-1.19.2-1.0.5.jar
TradingPost-v4.2.0-1.19.2-Fabric.jar
trinkets-3.4.2.jar
veinmining-fabric-1.1.1+1.19.2.jar
vmp-fabric-mc1.19.2-0.2.0+beta.7.29-all.jar
WhiteRabbit-1.1.1+1.14.4-1.19.3.jar
worldedit-mod-7.2.12.jar
wraith-waystones-3.0.7+mc1.19.2.jar
wthit-fabric-5.16.0.jar
XaerosWorldMap_1.30.2_Fabric_1.19.1.jar
Xaeros_Minimap_23.4.3_Fabric_1.19.1.jar
YetAnotherConfigLib-2.2.0-for-1.19.2.jar
youre-in-grave-danger-1.4.9.jar
YungsApi-1.19.2-Fabric-3.8.9.jar
YungsBetterDesertTemples-1.19.2-Fabric-2.2.2.jar
YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
YungsBetterNetherFortresses-1.19.2-Fabric-1.0.5.jar
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0.jar
YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
YungsBridges-1.19.2-Fabric-3.1.0.jar
YungsExtras-1.19.2-Fabric-3.1.0.jar
Zoomify-2.9.0.jar

**Comment by StevenCrazyFire** [comment]
what server is the IP? i wanna join plz
