### ISSUE TITLE
Error printed once per tick when on non-default (non-player) Identity

### ISSUE THREAD

**Issue by James103** [Draylar/identity#7]
While you are disguised, the following error is printed to the logs every tick:
```
[15:39:34] [main/FATAL]: Error executing task on Client
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_1297.method_5651(class_1297.java:1645) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at draylar.identity.cca.IdentityComponent.fromTag(IdentityComponent.java:108) ~[identity-1.0.3-beta-1.16.jar:?]
	at nerdhub.cardinal.components.api.util.sync.BaseSyncedComponent.readFromPacket(BaseSyncedComponent.java:69) ~[8c5efe8a-2222-484c-aacd-86f2a86ab2cb.jar:?]
	at nerdhub.cardinal.components.api.util.sync.EntitySyncedComponent.processPacket(EntitySyncedComponent.java:96) ~[3b92d36e-8780-4865-bbec-f7846042407d.jar:?]
	at nerdhub.cardinal.components.CardinalComponentsEntity.lambda$initClient$5(CardinalComponentsEntity.java:84) ~[3b92d36e-8780-4865-bbec-f7846042407d.jar:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_241]
	at nerdhub.cardinal.components.CardinalComponentsEntity.lambda$initClient$6(CardinalComponentsEntity.java:84) ~[3b92d36e-8780-4865-bbec-f7846042407d.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:988) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.1-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.8+build.202.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.8+build.202.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.8+build.202.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: net.minecraft.class_638 cannot be cast to net.minecraft.class_3218
	at net.minecraft.class_1560.method_5749(class_1560.java:214) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1636) ~[intermediary-minecraft-1.16.1-client.jar:?]
	... 28 more
```

This is done using the following versions:
* Minecraft 1.16.1
* Fabric 0.8.8+build.202
* LWJGL 3.2.2
* Fabric API 0.14.0+build.371-1.16
* Identity 1.0.3-beta-1.16

Applies for following Identities:
* Zombie Pigman
* Enderman

**Comment by Draylar** [comment]
This is a vanilla bug. I [tried to report it today](https://bugs.mojang.com/browse/MC-192362) for a different reason, but my post was shot down, so we'll just have to wait until it's fixed. Seems like the current tracking post is [here](https://bugs.mojang.com/browse/MC-189565).

**Comment by James103** [comment]
Can you still reproduce this? If not, is it okay if you unpin this issue as it seems to be outdated?

**Comment by Draylar** [comment]
Good point: while the issue still exists in 1.16.5, it won't happen with Identity due to my patch.
